import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async';
import 'firebase_options.dart'; // This will be generated by FlutterFire CLI

/// Firebase Service - Handles connection to Firebase/Firestore
///
/// This service manages:
/// - Firebase initialization
/// - Connection status monitoring
/// - Error tracking and reporting
class FirebaseService {
  static final FirebaseService _instance = FirebaseService._internal();

  FirebaseService._internal();

  factory FirebaseService() {
    return _instance;
  }

  // Streams
  final _connectionStatusController = StreamController<bool>.broadcast();
  final _errorController = StreamController<String>.broadcast();

  // Getters for streams
  Stream<bool> get connectionStatus => _connectionStatusController.stream;
  Stream<String> get errors => _errorController.stream;

  bool _isInitialized = false;
  bool _isConnected = false;

  bool get isInitialized => _isInitialized;
  bool get isConnected => _isConnected;

  /// Initialize Firebase
  Future<void> initialize() async {
    try {
      if (_isInitialized) {
        _addInfo('Firebase already initialized');
        return;
      }

      _addInfo('Initializing Firebase...');

      // Initialize Firebase
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      _isInitialized = true;
      _addInfo('Firebase initialized successfully');

      // Try to establish Firestore connection
      await _checkConnection();
    } catch (e) {
      _isInitialized = false;
      _addError('Firebase initialization failed: $e');
      rethrow;
    }
  }

  /// Check and monitor Firestore connection
  Future<void> _checkConnection() async {
    try {
      _addInfo('Checking Firestore connection...');

      final firestore = FirebaseFirestore.instance;

      // Test connection with a simple query
      try {
        await firestore.collection('_connection_test').limit(1).get();
        _setConnected(true);
        _addInfo('Firestore connection verified');
      } catch (e) {
        _setConnected(false);
        _addError('Firestore connection test failed: $e');
      }
    } catch (e) {
      _setConnected(false);
      _addError('Firestore connection check failed: $e');
    }
  }

  /// Get Firestore instance
  FirebaseFirestore getFirestore() {
    if (!_isInitialized) {
      throw Exception('Firebase not initialized. Call initialize() first.');
    }
    return FirebaseFirestore.instance;
  }

  /// Private helper methods
  void _setConnected(bool connected) {
    if (_isConnected != connected) {
      _isConnected = connected;
      _connectionStatusController.add(connected);
    }
  }

  void _addError(String error) {
    print('❌ ERROR: $error');
    _errorController.add(error);
  }

  void _addInfo(String info) {
    print('ℹ️  INFO: $info');
  }

  /// Cleanup
  void dispose() {
    _connectionStatusController.close();
    _errorController.close();
  }
}
