// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGuSU9UxXB3H-5nAtM7oyGfNj6F1tlmP4',
    appId: '1:1028727617166:web:a955bcf08533b85fc03bdf',
    messagingSenderId: '1028727617166',
    projectId: 'tiles-selling-bms',
    authDomain: 'tiles-selling-bms.firebaseapp.com',
    databaseURL: 'https://tiles-selling-bms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiles-selling-bms.firebasestorage.app',
    measurementId: 'G-4J04JWRM12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9JXSi9hhI2dEGbHAgN3uss2ami3NBu8',
    appId: '1:1028727617166:android:64c02e4c891a2d20c03bdf',
    messagingSenderId: '1028727617166',
    projectId: 'tiles-selling-bms',
    databaseURL: 'https://tiles-selling-bms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiles-selling-bms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrj20HEKv-uTsTalQkqEM39tyD1Ot8ooc',
    appId: '1:1028727617166:ios:6d219ac839bcfaa6c03bdf',
    messagingSenderId: '1028727617166',
    projectId: 'tiles-selling-bms',
    databaseURL: 'https://tiles-selling-bms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiles-selling-bms.firebasestorage.app',
    iosBundleId: 'com.example.tilesSellingBms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrj20HEKv-uTsTalQkqEM39tyD1Ot8ooc',
    appId: '1:1028727617166:ios:6d219ac839bcfaa6c03bdf',
    messagingSenderId: '1028727617166',
    projectId: 'tiles-selling-bms',
    databaseURL: 'https://tiles-selling-bms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiles-selling-bms.firebasestorage.app',
    iosBundleId: 'com.example.tilesSellingBms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGuSU9UxXB3H-5nAtM7oyGfNj6F1tlmP4',
    appId: '1:1028727617166:web:351233e9f7882fe9c03bdf',
    messagingSenderId: '1028727617166',
    projectId: 'tiles-selling-bms',
    authDomain: 'tiles-selling-bms.firebaseapp.com',
    databaseURL: 'https://tiles-selling-bms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiles-selling-bms.firebasestorage.app',
    measurementId: 'G-XTB0TNRLXY',
  );
}
